import { Inter } from 'next/font/google'
import './globals.css'
import Image from "next/image"

const inter = Inter({ subsets: ['latin'] })
const marca = "/logo.svg"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import { UserIcon } from '@heroicons/react/24/outline'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       {/* <header className='absolute flex justify-start h-[8rem] w-screen pl-14 bg-gradient-to-b from-[#181410] via-[#181410a2]'> 
        <button className='w-1/12 font-mono text-[#E5D437] text-2xl flex items-center justify-around'><Image src={marca} width={100} height={100} className="h-12 text-[#E5D437]"/></button>
        </header> */}
        {children}
        </body>
    </html>
  )
}
